#!/usr/bin/env python3
"""Generate deterministic Fe tests using Python arbitrary-precision arithmetic.

Run from any directory. No packages or network needed. This oracle is independent
of the 512-bit modular inverse implementation under test. Solidity differential
execution is an additional pending gate, not replaced by these vectors.
"""
from pathlib import Path
import random

ROOT = Path(__file__).resolve().parents[1]
MAX = (1 << 256) - 1
rng = random.Random(0x554E495634)
vectors = [
    (0, 0, 1), (0, MAX, MAX), (MAX, 1, 1), (MAX, MAX, MAX),
    (MAX, MAX, MAX - 1), (1, 1, 0), (0, 0, 0),
    (1 << 128, 1 << 128, 2),
    (1 << 128, 1 << 128, 1),
    (MAX, MAX - 1, MAX),
    (MAX - 1, MAX - 1, MAX - 2),  # floor fits, ceil overflows
    (1, 1, 2), (6, 7, 3),
]
for _ in range(96):
    a, b = rng.getrandbits(256), rng.getrandbits(256)
    high = (a * b) >> 256
    vectors.extend((a, b, d) for d in (high, high + 1, rng.getrandbits(256)))
for exponent in range(256):
    vectors.append((MAX, 1 << exponent, 1 << exponent))

out = ['// Generated by tests/generate_math_vectors.py; do not edit.',
       'use super::full_math::{mul_div, mul_div_rounding_up}',
       'use super::bit_math::{most_significant_bit, least_significant_bit}', '']
for index, (a, b, d) in enumerate(vectors):
    for name, rounding in [('mul_div', False), ('mul_div_rounding_up', True)]:
        result = (a * b + (d - 1 if rounding else 0)) // d if d else MAX + 1
        reverts = result > MAX
        out.extend([
            '#[test(should_revert)]' if reverts else '#[test]',
            f'fn vector_{index}_{name}() {{',
            f'    let result = {name}({hex(a)}, {hex(b)}, {hex(d)})',
            '' if reverts else f'    assert!(result == {hex(result)})',
            '}', '',
        ])
# Each bit position, neighboring boundaries and arbitrary multi-bit words.
bit_inputs = {1, MAX}
for i in range(256):
    bit_inputs.update((1 << i, (1 << i) | 1, MAX ^ ((1 << i) - 1)))
bit_inputs.update(rng.getrandbits(256) for _ in range(64))
for index, value in enumerate(sorted(bit_inputs)):
    out.extend([
        '#[test]', f'fn bit_vector_{index}() {{',
        f'    assert!(most_significant_bit({hex(value)}) == {value.bit_length() - 1})',
        f'    assert!(least_significant_bit({hex(value)}) == {(value & -value).bit_length() - 1})',
        '}', '',
    ])
for name in ['most_significant_bit', 'least_significant_bit']:
    out.extend(['#[test(should_revert)]', f'fn {name}_zero_reverts() {{', f'    {name}(0)', '}', ''])
(ROOT / 'src/math_vectors.fe').write_text('\n'.join(out))
print(f'Generated {len(vectors) * 2} division and {len(bit_inputs) + 2} bit tests')
