// SPDX-License-Identifier: MIT
// Calldata parameter heads are checked before selfOnly; scalar/tail validation
// is deferred until the quote implementation accesses fields, as in Solidity.
use core::abi::{AbiSize, AbiDecoder, ByteInput, Decode, Encode, checked_frame_end}
use std::abi::{Bytes, DynArray, Sol, sol::{Uint24, Int24}}
use std::evm::Address
use super::{pool_types::PoolKey, path_key::PathKey, quoter::{QuoteSingle, QuoteMulti}}
pub struct Single {
    pub poolKey: PoolKey,
    pub zeroForOne: bool,
    pub exactAmount: u128,
    pub hookData: Bytes,
}
impl Single {
    pub fn from(_ value: own QuoteSingle) -> Self {
        Self { poolKey: value.0, zeroForOne: value.1, exactAmount: value.2, hookData: value.3 }
    }
}
impl AbiSize for Single {
    const HEAD_SIZE: u256 = 256
    const IS_DYNAMIC: bool = true
    fn payload_size(self) -> u256 {
        256 + self.hookData.payload_size()
    }
}
impl Decode<Sol> for Single {
    fn decode_payload<D: AbiDecoder<Sol>>(_ d: mut D) -> Self {
        checked_frame_end<Sol>(d.pos(), Self::HEAD_SIZE, d.input().len())
        Self {
            poolKey: PoolKey {
                currency0: Address { inner: 0 },
                currency1: Address { inner: 0 },
                fee: Uint24 { val: 0 },
                tickSpacing: Int24 { val: 0 },
                hooks: Address { inner: 0 },
            },
            zeroForOne: false,
            exactAmount: 0,
            hookData: Bytes::from_word_prefix(word: 0, len: 0),
        }
    }
}
impl Encode<Sol> for Single {
    fn encode(own self, _ ptr: *u8) {
        <QuoteSingle as Encode<Sol>>::encode(
            (self.poolKey, self.zeroForOne, self.exactAmount, self.hookData),
            ptr,
        )
    }
}
pub struct Multi { pub exactCurrency: Address, pub path: DynArray<PathKey>, pub exactAmount: u128 }
impl Multi {
    pub fn from(_ value: own QuoteMulti) -> Self {
        Self { exactCurrency: value.0, path: value.1, exactAmount: value.2 }
    }
}
impl AbiSize for Multi {
    const HEAD_SIZE: u256 = 96
    const IS_DYNAMIC: bool = true
    fn payload_size(self) -> u256 {
        96 + self.path.payload_size()
    }
}
impl Decode<Sol> for Multi {
    fn decode_payload<D: AbiDecoder<Sol>>(_ d: mut D) -> Self {
        checked_frame_end<Sol>(d.pos(), Self::HEAD_SIZE, d.input().len())
        Self { exactCurrency: Address { inner: 0 }, path: DynArray::empty(), exactAmount: 0 }
    }
}
impl Encode<Sol> for Multi {
    fn encode(own self, _ ptr: *u8) {
        <QuoteMulti as Encode<Sol>>::encode((self.exactCurrency, self.path, self.exactAmount), ptr)
    }
}
