// SPDX-License-Identifier: MIT
// v4-periphery SlippageCheck.sol at the pinned reference revision.
use std::evm::revert_error
use super::{balance_delta::BalanceDelta, safe_cast}
#[error]
pub struct MaximumAmountExceeded { pub maximumAmount: u128, pub amountRequested: u128 }
#[error]
pub struct MinimumAmountInsufficient { pub minimumAmount: u128, pub amountReceived: u128 }
pub fn validate_min_out(_ delta: BalanceDelta, _ minimum0: u128, _ minimum1: u128) {
    let a = safe_cast::signed_to_uint128(delta.amount0())
    if a < minimum0 {
        revert_error(
            MinimumAmountInsufficient { minimumAmount: minimum0, amountReceived: a },
        )
    }
    let b = safe_cast::signed_to_uint128(delta.amount1())
    if b < minimum1 {
        revert_error(
            MinimumAmountInsufficient { minimumAmount: minimum1, amountReceived: b },
        )
    }
}
pub fn validate_max_in(_ delta: BalanceDelta, _ maximum0: u128, _ maximum1: u128) {
    let a = delta.amount0() as i256
    let b = delta.amount1() as i256
    if a < 0 {
        let amount: u128 = (-a).downcast_truncate()
        if maximum0 < amount {
            revert_error(
                MaximumAmountExceeded { maximumAmount: maximum0, amountRequested: amount },
            )
        }
    }
    if b < 0 {
        let amount: u128 = (-b).downcast_truncate()
        if maximum1 < amount {
            revert_error(
                MaximumAmountExceeded { maximumAmount: maximum1, amountRequested: amount },
            )
        }
    }
}
